import React, { useState, useRef } from "react";
import { Upload, FileText, Settings, Info, Cpu } from "lucide-react";
import { motion } from "motion/react";
import { parseHWiNFOCSV } from "../utils/parser";
import { ParsedLog } from "../types";

interface UploadZoneProps {
  onLogParsed: (log: ParsedLog) => void;
  onShowAbout: () => void;
  onError: (err: string) => void;
}

export default function UploadZone({ onLogParsed, onShowAbout, onError }: UploadZoneProps) {
  const [isDragActive, setIsDragActive] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const processFile = (file: File) => {
    if (!file) return;
    
    // Accept only CSV or text files (case-insensitive)
    const fileNameLower = file.name.toLowerCase();
    if (!fileNameLower.endsWith(".csv") && !fileNameLower.endsWith(".txt")) {
      onError("Please upload a standard HWiNFO .csv or .txt log file.");
      return;
    }

    setIsLoading(true);
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        if (!text) {
          throw new Error("Unable to read file content.");
        }
        const parsed = parseHWiNFOCSV(text);
        if (parsed.sampleCount === 0) {
          throw new Error("The uploaded file contains no samples. Please upload a valid log file.");
        }
        onLogParsed(parsed);
      } catch (err: any) {
        console.error(err);
        onError(err.message || "Failed to parse the log. Please verify it is a valid HWiNFO CSV file.");
      } finally {
        setIsLoading(false);
      }
    };
    reader.onerror = () => {
      onError("Error reading file.");
      setIsLoading(false);
    };
    reader.readAsText(file);
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setIsDragActive(true);
    } else if (e.type === "dragleave") {
      setIsDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[80vh] px-4 py-8">
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="text-center mb-8"
      >
        <div className="flex items-center justify-center gap-2 mb-2">
          <Cpu className="w-10 h-10 text-cyan-400" />
          <h1 id="app-title" className="text-4xl font-extrabold tracking-tight text-white bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
            HWiNFO Log Analyser
          </h1>
        </div>
        <p className="text-slate-400 max-w-lg mx-auto text-sm mt-2 leading-relaxed">
          Unlock insights into your computer's performance. Upload the log generated by HWiNFO to visualise temperatures, power draw, clock speeds, throttling and more in stunning detail.
        </p>
      </motion.div>


      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden p-8 relative"
      >
        {/* Decorative corner grid or elements */}
        <div className="absolute top-0 left-0 w-16 h-16 border-t-2 border-l-2 border-cyan-500/20 rounded-tl-2xl pointer-events-none" />
        <div className="absolute top-0 right-0 w-16 h-16 border-t-2 border-r-2 border-cyan-500/20 rounded-tr-2xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-16 h-16 border-b-2 border-l-2 border-cyan-500/20 rounded-bl-2xl pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-16 h-16 border-b-2 border-r-2 border-cyan-500/20 rounded-br-2xl pointer-events-none" />

        <input
          ref={fileInputRef}
          type="file"
          accept=".csv,.txt"
          onChange={handleFileChange}
          className="hidden"
          id="file-upload-input"
        />

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-16 space-y-4">
            <div className="relative w-16 h-16">
              <div className="absolute inset-0 rounded-full border-4 border-slate-800" />
              <div className="absolute inset-0 rounded-full border-4 border-cyan-400 border-t-transparent animate-spin" />
            </div>
            <p className="text-cyan-400 font-medium font-mono text-sm animate-pulse">
              ANALYSING LOG CHANNELS...
            </p>
          </div>
        ) : (
          <div
            onDragEnter={handleDrag}
            onDragOver={handleDrag}
            onDragLeave={handleDrag}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl p-10 flex flex-col items-center justify-center cursor-pointer transition-all duration-300 group ${
              isDragActive
                ? "border-cyan-400 bg-cyan-950/20 shadow-[0_0_20px_rgba(34,211,238,0.15)] scale-[1.01]"
                : "border-slate-800 hover:border-slate-700 bg-slate-950/40 hover:bg-slate-950/60"
            }`}
            id="drag-drop-zone"
          >
            <div className={`p-4 rounded-full mb-4 transition-transform duration-300 group-hover:scale-110 ${
              isDragActive ? "bg-cyan-500/20 text-cyan-400" : "bg-slate-900 text-slate-400 group-hover:text-cyan-400"
            }`}>
              <Upload className="w-8 h-8" />
            </div>
            
            <p className="text-white font-medium text-lg mb-1 group-hover:text-cyan-400 transition-colors">
              Drag & drop your HWiNFO log here
            </p>
            <p className="text-slate-500 text-sm mb-6">
              or <span className="text-cyan-400 underline decoration-dotted">browse files</span> on your computer (.csv, .txt)
            </p>

            <div className="flex flex-wrap justify-center gap-3 text-xs text-slate-400 bg-slate-900/60 py-2.5 px-4 rounded-lg border border-slate-800/80">
              <span className="flex items-center gap-1 font-mono text-[11px] text-slate-500">
                <FileText className="w-3.5 h-3.5 text-slate-500" /> Comma-separated (,)
              </span>
            </div>
          </div>
        )}

        <div className="mt-8 border-t border-slate-800/80 pt-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-start gap-2.5 max-w-md">
              <Info className="w-4.5 h-4.5 text-cyan-500 shrink-0 mt-0.5" />
              <div className="text-left">
                <h4 className="text-xs font-semibold text-slate-300">Quick Guide to HWiNFO Logging</h4>
                <p className="text-[11px] text-slate-400 leading-relaxed mt-1">
                  Click the green "+" icon with the spreadsheet (or the "Logging Start" button) at the bottom of the HWiNFO Sensors screen to save your log file. Perform your test, then upload it here.
                </p>
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="mt-8 flex justify-center"
      >
        <button
          onClick={(e) => {
            e.stopPropagation();
            onShowAbout();
          }}
          className="group flex items-center gap-2 px-4 py-2 rounded-full bg-slate-800/40 hover:bg-slate-700/60 border border-slate-700/50 transition-all duration-300 text-slate-400 hover:text-slate-200 text-xs font-medium"
        >
          <Info className="w-3.5 h-3.5" />
          About Project
        </button>
      </motion.div>
    </div>
  );
}
